language: python
python:
  - '3.8.2'

# safelist
branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=travis.travis

script:
  - ./manage.py test