# Generated by Django 3.1.6 on 2021-03-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0016_auto_20210225_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.product')),
                ('substitute', models.ForeignKey(db_column='substitute_barcode', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_substitutes', to='products.product')),
            ],
        ),
    ]
