# Generated by Django 3.1.6 on 2021-02-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210223_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(),
        ),
    ]
